services:
  user-service:
    image: fieldmanagementsystem-user:latest
    container_name: fms-user-service
    ports:
      - '8081:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Logging__Seq__ServerUrl: http://seq
    networks:
      - fsm_shared_network
    restart: unless-stopped

networks:
  fsm_shared_network:
    external: true